### 주문 준비
POST {{endpoint}}/api/order/prepare
content-type: application/json
x-User-Id: {{x-user-id}}

{
  "orderItems": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### 주문
@order_id = 5336389640443376971
POST {{endpoint}}/api/order/{{order_id}}/pay
x-User-Id: {{x-user-id}}

### 주문 취소
POST {{endpoint}}/api/order/{{order_id}}/refund
x-User-Id: {{x-user-id}}