### 회원가입
POST {{endpoint}}/api/public/user/register
content-type: application/json

{
  "name": "김유미",
  "birthDate": "2000-11-10",
  "phoneNumber": "01012341234",
  "gender": "FEMALE"
}

### 회원 탈퇴
DELETE {{endpoint}}/api/user/withdraw
x-User-Id: {{x-user-id}}

### 회원 탈퇴 철회
POST {{endpoint}}/api/user/revoke-withdrawal
x-User-Id: {{x-user-id}}