spring:
  datasource:
    url: jdbc:h2:mem:payment_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

---
# Local 환경 (개발자 로컬)
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    com.cafe.payment: DEBUG

---
# Dev 환경 (개발 서버)
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.orm.jpa: INFO
    com.cafe.payment: INFO
    org.hibernate.SQL: WARN 